### PR TITLE
merged  operations for +-*

### PR DESCRIPTION
**Pull request by scifuentes**
Consecutive sums/subtractions/multiplications are merged into the same transformation instead of nested as independent ones
eg: cube(1)+cube(2)+cube(3)

current, nested:
```
union() { 
	union() {
		cube(size = 1);
		cube(size = 2);
	}
	cube(size = 3);
}
```
proposed, merged:
```
union() {
	cube(size = 1);
	cube(size = 2);
	cube(size = 3);
}
```
While it do not seems to have any notable impact on the render time at OpenScad for the difference and intersection transforms it have a considerable impact for the unions: On the simple case below it cut the render time to a third, on other cases the nested code just hanged there for many minutes -till patience run out actually- while it took ~1min for the merged code to render

Simple test case, render time:
union :
```python
scene = cube(2)
for i in range(100):
    scene += translate([i,i,0])(cube(2))
```
OpenScad console output ...
* Nested:
```
    Compiling design (CSG Tree generation)...
    Rendering Polygon Mesh using CGAL...
    Geometries in cache: 101
    Geometry cache size in bytes: 73528
    CGAL Polyhedrons in cache: 101
    CGAL cache size in bytes: 55432592
    Total rendering time: 0 hours, 1 minutes, 3 seconds
       Top level object is a 3D object:
       Simple:        yes
       Vertices:      800
       Halfedges:    2400
       Edges:        1200
       Halffacets:    804
       Facets:        402
       Volumes:         2
    Rendering finished.
```
* Merged:
```
    Compiling design (CSG Tree generation)...
    Rendering Polygon Mesh using CGAL...
    Geometries in cache: 101
    Geometry cache size in bytes: 73528
    CGAL Polyhedrons in cache: 2
    CGAL cache size in bytes: 2151584
    Total rendering time: 0 hours, 0 minutes, 19 seconds
       Top level object is a 3D object:
       Simple:        yes
       Vertices:      800
       Halfedges:    2400
       Edges:        1200
       Halffacets:    804
       Facets:        402
       Volumes:         2
    Rendering finished.
```

### CODE REVIEW

**Comment by evandrone** [comment]
That's a really interesting optimization! It may take me a few days to take a look at this as deeply as it deserves, but congratulations for speeding things up so much!

**Comment by evandrone** [comment]
Sorry I left this for so long.  This is great!

**Comment by etjones** [comment]
Don't know if you're getting notified there, @conorpp, but I opened Issue #79 to handle this.  Haven't been able to duplicate this problem yet, but would appreciate input over at #79 if you can help with bug duplication.  Cheers!

**Comment by conorpp** [comment]
Hey @etjones, sorry I looks like I missed a step.  This should duplicate the bug (tested this time).

```python
    r = cube(10)

    r -= cube(1)  # missed step

    p = cube(10)
    p = r * p

    r -= p

    scad_render(r)
```

**Pull request merged**
