### PR TITLE
Pep8 objects

### PR DESCRIPTION
**Pull request by Cabalist**
Hey there,

This is a really great project!   I really appreciate the Type Hinting that was added to it.   :) 

While reading through the code I've done some quick trivial cleanup.  This is just the `objects.py` file.   Each commit should be one cleanup step.  I don't think anything is too controversial here but I thought I would start small.  

The bigger changes that could be a point of discussion are:

- Use `super()` syntax where appropriate : 
  This permits subclassing and more flexible code.  It is functionally the same as `OpenSCADObject.__init__(...` but permits inheritance and the possibility of mixins in the future.  There may be a reason that OpenSCADObject was explicitly being called but I didn't see one.

- Add `-> None` to cls.__init_ calls per PEP484 : 
  My linter was complaining about this.   I've been part of discussions where this seems sort of boilerplate-y but it reduces the amount of ignorable warnings in the type checkers that can hide actual issues.

This project has been really fun to use.  Thanks for all your hard work!

### CODE REVIEW

**Comment by etjones** [comment]
Solid. Done!  Thanks for the cleanup!

**Comment by etjones** [comment]
Hey - Auto-merging caused [test failures](https://circleci.com/gh/SolidCode/SolidPython/107) and some other issues. In your branch if you run `solid/test/run_all_tests.sh` do things work OK? I'd love to re-merge these changes, but I want to make sure that tests & mypy both complete successfully before putting this back in master. Cheers!

**Comment by Cabalist** [comment]
Looking into this now.   I'm getting a `ModuleNotFoundError: No module named 'solid'` when running that script.  Anything else I need to do?

**Comment by Cabalist** [comment]
It looks like it is caused by the inclusion/exclusion of  `from .solidpython import IncludedOpenSCADObject` in this file.   

This is likely caused by one of the `import *` pulling this in as a side effect.  I'll have an answer shortly.

**Comment by etjones** [comment]
Thanks. I know Guido has his reasons for Python 3's import mechanisms, but I do find they bite me more than Python 2's did. This might be a problem with my incomplete understanding of that mechanic

**Comment by Cabalist** [comment]
Got it.  It looks like the `import *` in `solid/__init__.py` was pulling it in the long way round.  I made it explicit.  I'll revisit this code later on to see if I can get rid of the `import *`s in general.  It is kind of fraught has the possibility of changing the API but is much better down the road as the API is explicit and will have less surprises like the one we just saw

**Comment by Cabalist** [comment]
Hmm...  How would you like me to restage these commits?   New PR?

**Comment by etjones** [comment]
I think that's the way to go; I was looking to see if there was a way to revive this one, but if you can make one single big PR ( or add to #119 that you just created), that would be great.

**Comment by etjones** [comment]
I've looked at how to run CI on PRs before, but never quite figured it out. Now's my chance!

**Comment by Cabalist** [comment]
Cool.  Check out #120 I think that was the cleanest way to do that without a force push to master.  :)

**Pull request merged**
