### PR TITLE
adding initial support for IPython (Notebook)

### PR DESCRIPTION
**Pull request by bollwyvl**
## Observed Behavior
From within an IPython interactive session, `master` complains about `calling_module` returning `None` when many features (`use`, `include`, etc.) are called. 

## Proposed
This PR adds a small workaround that will try to use the current IPython user namespace if the module is `None`, and the frame bears IPython-y marks. It should have little impact beyond that

Currently, many features in `solid` require a real module for the stack to find. IPython, in emulating the REPL, does a lot of its own magic with the stack, which [`inspect.getmodule`](https://docs.python.org/2/library/inspect.html#inspect.getmodule) can't quite figure out: the behavior of that function is best-effort, anyway. 

I can add tests, if you would like, but then IPython would at least need to be added to the test regime. 

## Motivation
[IPython](http://ipython.org)/[Jupyter](http://jupyter.org) (specifically the notebook) offers a productive, interactive, web-based interface for writing, among other things, python. The notebook format is a JSON which stores code, narrative, and output. Recently, it was also added as a format directly rendered in Github (within limits, because XSS) but can also be viewed on [nbviewer](http://nbviewer.org). _Disclosure: i'm an nbviewer maintainer!_

## Appropriateness
While this could be implemented as a monkeypatch, I think there are enough people that will be experiencing Python for the first time through the notebook interface that I would hope you wouldn't mind including it.

## Future work
As I am experimenting, I will very likely gin up:
- some IPython widgets (think sliders, etc.) that control parameters, regenerate the file, causing the OpenSCAD GUI to update
- a BOM viewer
- an in-notebook STL viewer, perhaps [thingiviewer](http://wiki.ultimaker.com/thingiview.js/examples/client_side_ajax.html#)... likely this would still shell out to openscad to generate the file, but then it would become embedded in the notebook itself... great for sharing!

These kinds of features could easily be a separate module, e.g. `ipysolid` but I would be very happy to contribute them to this project, whether in some `contrib` section, or what have you.

### CODE REVIEW

**Comment by etjones** [comment]
Thanks for working on this!  I haven't regularly used SP from an interactive shell, so I'd overlooked this problem in the stack examination scheme I was using in `calling_module()`. 

I use IPython all day long, so if there's anything I'm likely to want  SP to integrate with, that's it. That said, I suspect that importing IPython explicitly in this case may just be a workaround for some sloppy work I did in `calling_module()`.  What I'd prefer to do is fix the source of the problem rather than apply an IPython-shaped bandage to it.  Let me get back to you once I've looked at the source a little further.  

 The future work you're talking about would be awesome, and I'd be very open to some explicit IPython integration for notebooks & the like.  Let me know if you've got some more ideas.

**Comment by bollwyvl** [comment]
Thanks for the feedback!

I'm all for fixing the underlying problem, but importing is kind of a magic thing at the best of times... I'm not sure I know enough how to suggest fixing it. But good luck!

Here's a [wee example](http://nbviewer.ipython.org/gist/bollwyvl/ad2bb78de14d876bbcc3/Basic%20Geometry.ipynb) of the thing I had imagined: screenshot didn't work, but you can see it [here](https://gist.github.com/bollwyvl/ad2bb78de14d876bbcc3). While the widget frontend stuff is nice, the real money is that widgets are traitful (i.e. evented) objects that can be linked to other traitful objects.

A less widget-based integration would add some `__repr_javascript__` to the various solidpython objects that would make them more explorable... not sure yet!

**Comment by etjones** [comment]
Hey - I took a look at this and came up with what I think is a [minimal solution](https://github.com/SolidCode/SolidPython/compare/feature/interactive_use_fix_20150523)  that doesn't introduce any extra dependencies.  It works for me in IPython and a standard Python shell.  Do you think this would work for your purposes?  Let me know if it doesn't play nicely with your notebook work, and I'll rethink it.  (I'm just returning` __main__`, the top level module, rather than  `IPython.get_ipython().user_module`)

Here was my minimal test, run from `SolidPython/solid/examples`:

```python
from solid import *
use('scad_to_include.scad') # Raises Exception in master: bca81c36a0988e6983e394de061343fc5f38d685, 
                            # succeeds in branch: feed5bae37f8288e2913d5be3b86c22a4e736236 
a = steps(5)
scad_render_to_file(a) # writes to 'SolidPython/solid/examples/solid.scad' 

```

Let me know about any further work you get up to w.r.t. notebook integration; I think it's a great thing and I'd be happy to enable that work however possible.

**Comment by bollwyvl** [comment]
That fix works beautifully, closing. Thanks!

Also congratulations on PEP8 :) Once you take the plunge, I find it's important to work it into a `.travis.yml`... first off, this makes PRs easier, second it makes you be explicit about what subset of PEP8 you are expecting, rather than relying on personal standards. I can help out if you'd like :)

Here is the thing I am working on:
http://nbviewer.ipython.org/github/bollwyvl/crib/blob/master/Crib.ipynb

This is me evolving my toolset along with my task, so it's hardly in its best form... and includes some of my other experiments as well (like [ipytangle](/bollwyvl/ipytangle)). To get it to work, I do have to comment out the [segments param thing](https://github.com/SolidCode/SolidPython/blob/master/solid/solidpython.py#L452), which I meant to raise as an issue...

Anyhow, in terms of integration: I've already created #37, which is a simple, no-dependency way to increase the impact of SP in the notebook.

Other thoughts (some related to IPython):

In the Crib example above, I'll want to have inline renderings that update as people interact with the text narrative (which is secretly made of widgets)... there are a few ways to do this, but widgets are probably the best way. In essence, I'll wrap my functional logic inside a bunch of traitlet event handlers. I'll probably just hack it together at first.

However, I think a first-class widget layer would be mind-blowing: basically, an evented model on top of solid that new how to rebuild and display itself when values changed, as well as cause other values to be updated. Unfortunately, you rapidly run up against a need for a solver... but the end result (again, once an interactive representation is possible) would be pretty amazing.

The present BOM, with its global stuff, is not very useful in an interactive setting. I ended up rolling my own, as I was adding up gridbeam stuff, and just wanted a total board foot sum. It seems like some metadata facility that could be additive through the tree (what does a BOM intersection mean? machines required?) would solve this neatly, and lead the way for other things (tool path description, costs, etc.) Very powerful stuff.

Thanks again!

**Pull request closed without merging**
