### PR TITLE
Cleanup tests

### PR DESCRIPTION
**Pull request by Cabalist**
Similar to previous PR.  Focuses on removing `import *`

### CODE REVIEW

**Comment by Cabalist** [comment]
Friendly bump on this one since some other PRs got merged.

**Comment by etjones** [comment]
Sorry, hadn't noticed this one. However... there's some change to tabular data formatting in the tests that I need to think over a bit. I know Pep 8 is not in favor of spacing in code, but I sometimes am.  Let me revisit this one tomorrow.

**Comment by Cabalist** [comment]
No rush and understandable.

**Comment by Cabalist** [comment]
This seems to have caused a test failure.  I'm investigating now

**Comment by etjones** [comment]
Me too.

**Pull request merged**
